### ISSUE TITLE
Tetgen crash on big meshes

### ISSUE THREAD

**Issue by jvwilliams23** [aurora-multiphysics/libmeshSkinning#24]
Hi,

Me again 😮. I am using VacuumMesher through singularity on CSD3 icelake high memory nodes (around 500 GB RAM). Trying to get a vacuum mesh for the CHIMERA CSUT geometry:

``` bash
/opt/VacuumMesher/build/bin/vacuum -v -i csut-thermal.e -o csut-thermal-vac.e --bound_len 6
```

It seems to be working well and then at some point, tetgen crashes. I initially thought it was running out of memory, but I have been monitoring it with `watch`, the used never really goes above ~35 GB. Have you experienced this before? Any ideas how to fix it? 

```
Refining mesh...
  Min radius-edge ratio = 2.
  Min dihedral   angle  = 3.5.
  Splitting bad quality tets.
  Added 174768 (0,0,174768) Steiner points.
  Added 4 (0,0,4) Steiner points.
  Added 0 (0,0,0) Steiner points.
Refinement seconds:  22.0097
Smoothing vertices...
  Smooth criterion   = 3
  Smooth iterations  = 7
  Smooth relax-alpha = 0.3
Mesh smoothing seconds:  23.4737
Improving mesh...
  Target maximum aspect ratio = 1000.
  Target maximum dihedral angle = 177.
  Maximum flip level   = 3.
  Number of iterations = 3.
^tetrahedralize: TETGEN CRASHED...KABOOM!!
libMesh terminating:
You are calling closestPair3D for a mesh which is not 3D!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

```

**Comment by jvwilliams23** [comment]
I think it is just an issue with the CHIMERA mesh, maybe a bad quality cell somewhere. I created a similar sized mesh of a simpler geometry, and it worked fine.

**Comment by makeclean** [comment]
Is this the solid thermal problem?

**Comment by jvwilliams23** [comment]
I am using the csut-thermal.e mesh you sent me for the thermo-mechanical problem, yes. But I am trying to get a vacuum to do an EM sim.

**Comment by makeclean** [comment]
Fair, yeah there is an issue with the original mesh that means vacuum mesher wont work with it - the key assumption underlying vacumm mesher is that surfaces between volumes are topologically connected and merged, there is a single surface which isn't and this will break tetgen.

**Comment by makeclean** [comment]
let me try and make you a better one

**Comment by jvwilliams23** [comment]
@makeclean ok thanks, that would be great
